In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv")

In [3]:
print("Shape of the dataset:", df.shape)
print("First 5 rows:")
display(df.head())

print("Info:")
df.info()

print("Statistical Summary:")
display(df.describe(include="all"))

# Missing Values
print("Missing Values:")
display(df.isnull().sum().sort_values(ascending=False))

# Duplicates
print("Number of Duplicate Rows:", df.duplicated().sum())

# Data Types
print("Column Data Types:")
display(df.dtypes)

# Unique Values
print("Unique Values Per Column:")
display(df.nunique().sort_values(ascending=False))

Shape of the dataset: (2945, 149)
First 5 rows:

,league,season,team,player,nation,pos,age,born,Playing Time MP,Playing Time Starts,...,Standard Sh/90,Standard SoT/90,Standard FK,Standard PK,Standard PKatt,Expected xG_shooting,Expected npxG_shooting,Expected G-xG,Expected np:G-xG,stat_type_shooting
0,ESP-La Liga,2020,Atlético Madrid,Ángel Correa,ARG,"FW,MF",25.0,1995.0,38,29,...,1.96,0.87,0,0,0,7.8,7.7,1.2,1.3,shooting
1,ESP-La Liga,2020,Granada,Ángel Montoro,ESP,MF,32.0,1988.0,22,17,...,0.93,0.07,3,1,1,1.3,0.5,-0.3,-0.5,shooting
2,ESP-La Liga,2020,Getafe,Ángel Rodríguez,ESP,"FW,MF",33.0,1987.0,33,12,...,2.36,0.79,0,1,2,5.7,4.1,-0.7,-0.1,shooting
3,ESP-La Liga,2020,Real Madrid,Éder Militão,BRA,DF,22.0,1998.0,14,13,...,0.95,0.24,0,0,0,1.1,1.1,-0.1,-0.1,shooting
4,ESP-La Liga,2020,Elche,Édgar Badía,ESP,GK,28.0,1992.0,30,30,...,0.00,0.00,0,0,0,0.0,0.0,0.0,0.0,shooting

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2945 entries, 0 to 2944
Columns: 149 entries, league to stat_type_shooting
dtypes: float64(41), int64(87), object(21)
memory usage: 3.3+ MB
Statistical Summary:

,league,season,team,player,nation,pos,age,born,Playing Time MP,Playing Time Starts,...,Standard Sh/90,Standard SoT/90,Standard FK,Standard PK,Standard PKatt,Expected xG_shooting,Expected npxG_shooting,Expected G-xG,Expected np:G-xG,stat_type_shooting
count,2945,2945.000000,2945,2945,2945,2945,2945.000000,2945.000000,2945.000000,2945.000000,...,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2945.000000,2945
unique,1,NaN,27,1234,83,10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
top,ESP-La Liga,NaN,Sevilla,Carles Aleñá,ESP,DF,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shooting
freq,2945,NaN,156,8,1763,857,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2945
mean,NaN,2022.008489,NaN,NaN,NaN,NaN,25.991511,1995.646180,19.085229,13.562988,...,1.122200,0.347025,0.532428,0.154499,0.206452,1.590526,1.426655,-0.060475,-0.051104,NaN
std,NaN,1.407567,NaN,NaN,NaN,NaN,4.653291,4.944437,11.492223,11.005720,...,1.416874,0.551849,1.912768,0.703906,0.843871,2.694834,2.317005,1.090958,1.072776,NaN
min,NaN,2020.000000,NaN,NaN,NaN,NaN,15.000000,1979.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.200000,-6.300000,NaN
25%,NaN,2021.000000,NaN,NaN,NaN,NaN,22.000000,1992.000000,9.000000,3.000000,...,0.250000,0.000000,0.000000,0.000000,0.000000,0.100000,0.100000,-0.500000,-0.500000,NaN
50%,NaN,2022.000000,NaN,NaN,NaN,NaN,26.000000,1996.000000,21.000000,12.000000,...,0.750000,0.170000,0.000000,0.000000,0.000000,0.600000,0.600000,0.000000,0.000000,NaN
75%,NaN,2023.000000,NaN,NaN,NaN,NaN,29.000000,1999.000000,29.000000,23.000000,...,1.650000,0.500000,0.000000,0.000000,0.000000,1.800000,1.700000,0.200000,0.200000,NaN
max,NaN,2024.000000,NaN,NaN,NaN,NaN,41.000000,2007.000000,38.000000,38.000000,...,36.000000,11.250000,40.000000,10.000000,10.000000,24.300000,23.500000,10.700000,10.700000,NaN

Missing Values:

league                    0
season                    0
team                      0
player                    0
nation                    0
                         ..
Expected xG_shooting      0
Expected npxG_shooting    0
Expected G-xG             0
Expected np:G-xG          0
stat_type_shooting        0
Length: 149, dtype: int64

Number of Duplicate Rows: 0
Column Data Types:

league                     object
season                      int64
team                       object
player                     object
nation                     object
                           ...
Expected xG_shooting      float64
Expected npxG_shooting    float64
Expected G-xG             float64
Expected np:G-xG          float64
stat_type_shooting         object
Length: 149, dtype: object

Unique Values Per Column:

Total TotDist           2145
Total PrgDist           1804
Carries TotDist         1795
Playing Time Min        1519
Carries PrgDist         1483
                        ...
stat_type_possession       1
stat_type_misc             1
stat_type_defense          1
stat_type_passing          1
stat_type_shooting         1
Length: 149, dtype: int64

In [4]:
# Value Counts for Object (Categorical) Columns
cat_cols = df.select_dtypes(include="object").columns
for col in cat_cols:
    print(f"\n🧾 Value counts for: {col}")
    display(df[col].value_counts().head(10))
    print("-" * 50)

🧾 Value counts for: league

league
ESP-La Liga    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: team

team
Sevilla          156
Real Sociedad    152
Villarreal       150
Betis            150
Getafe           150
Valencia         149
Celta Vigo       147
Cádiz            140
Real Madrid      140
Athletic Club    137
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: player

player
Carles Aleñá        8
Takefusa Kubo       7
Manu Sánchez        7
Fernando            6
Portu               6
Carlos Fernández    6
Ezequiel Ávila      6
Nacho               6
Sergi Guardiola     6
Nacho Vidal         6
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation

nation
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos

pos
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type

stat_type
standard    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation_possession

nation_possession
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos_possession

pos_possession
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type_possession

stat_type_possession
possession    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation_misc

nation_misc
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos_misc

pos_misc
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type_misc

stat_type_misc
misc    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation_defense

nation_defense
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos_defense

pos_defense
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type_defense

stat_type_defense
defense    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation_passing

nation_passing
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos_passing

pos_passing
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type_passing

stat_type_passing
passing    2945
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: nation_shooting

nation_shooting
ESP    1763
ARG     147
FRA     102
BRA     101
URU      76
POR      66
MAR      48
SRB      48
COL      33
BEL      30
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: pos_shooting

pos_shooting
DF       857
MF       634
FW       399
FW,MF    294
MF,FW    289
GK       216
DF,MF    116
MF,DF     93
DF,FW     26
FW,DF     21
Name: count, dtype: int64

--------------------------------------------------

🧾 Value counts for: stat_type_shooting

stat_type_shooting
shooting    2945
Name: count, dtype: int64

--------------------------------------------------

In [5]:
# Percent of missing values
missing_ratio = df.isnull().mean() * 100
missing_ratio[missing_ratio > 0].sort_values(ascending=False)

Series([], dtype: float64)

In [6]:
constant_cols = [col for col in df.columns if df[col].nunique() == 1]
print("Constant columns:", constant_cols)

Constant columns: ['league', 'stat_type', 'stat_type_possession', 'stat_type_misc', 'stat_type_defense', 'stat_type_passing', 'stat_type_shooting']

In [7]:
# Check how many times each player appears
player_counts = df["player"].value_counts()
duplicate_players = player_counts[player_counts > 1]

print(f"Number of duplicate player names: {len(duplicate_players)}")
display(duplicate_players.head(10))

Number of duplicate player names: 853

player
Carles Aleñá        8
Takefusa Kubo       7
Manu Sánchez        7
Fernando            6
Portu               6
Carlos Fernández    6
Ezequiel Ávila      6
Nacho               6
Sergi Guardiola     6
Nacho Vidal         6
Name: count, dtype: int64

In [8]:
# List of dataset paths
file_paths = [
    "../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv",
    "../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv",
    "../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv",
    "../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv",
    "../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv",
]

for file_path in file_paths:
    print(f"Checking missing values in: {file_path}")

    try:
        df = pd.read_csv(file_path)

        # Calculate percentage of missing values per column
        missing_ratio = df.isnull().mean() * 100
        missing_ratio = missing_ratio[missing_ratio > 0].sort_values(ascending=False)

        if missing_ratio.empty:
            print("No missing values found.")
        else:
            print(f"Columns with missing values ({len(missing_ratio)}):")
            print(missing_ratio)

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
No missing values found.

In [9]:
# We remove the features with more than 5% of missing values in each data set (5% missing for all data set)
# Columns to drop
columns_to_drop = [
    "Standard G/SoT",
    "Standard G/Sh",
    "Standard SoT%",
    "Standard Dist",
    "Take-Ons Tkld%",
    "Take-Ons Succ%",
    "Challenges Tkl%",
    "Aerial Duels Won%",
    "Long Cmp%",
    "90s_possession",
    "90s_defense",
    "90s_misc",
    "90s_shooting",
    "Expected npxG/Sh",
    "Expected_shooting npxG/Sh",
]

# Loop through and process each file
for file_path in file_paths:
    print(f"Processing: {file_path}")

    try:
        df = pd.read_csv(file_path)

        # Drop columns that exist in this dataset
        drop_cols = [col for col in columns_to_drop if col in df.columns]
        df.drop(columns=drop_cols, inplace=True)

        # Save cleaned DataFrame back to the same file
        df.to_csv(file_path, index=False)
        print(f"Dropped {len(drop_cols)} columns and saved: {file_path}")

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

Processing: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
Dropped 0 columns and saved: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
Dropped 0 columns and saved: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
Dropped 0 columns and saved: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
Dropped 0 columns and saved: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
Dropped 0 columns and saved: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv

In [10]:
for file_path in file_paths:
    print(f"Checking missing values in: {file_path}")

    try:
        df = pd.read_csv(file_path)

        # Calculate percentage of missing values per column
        missing_ratio = df.isnull().mean() * 100
        missing_ratio = missing_ratio[missing_ratio > 0].sort_values(ascending=False)

        if missing_ratio.empty:
            print("No missing values found.")
        else:
            print(f"Columns with missing values ({len(missing_ratio)}):")
            print(missing_ratio)

    except Exception as e:
        print(f"⚠️ Error processing {file_path}: {e}")

Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
No missing values found.

In [11]:
# replace missing values with median for other variables :

for file_path in file_paths:
    print(f"Processing: {file_path}")

    try:
        df = pd.read_csv(file_path)

        numeric_cols = df.select_dtypes(include="number").columns
        for col in numeric_cols:
            if df[col].isnull().any():
                median_val = df[col].median()
                df[col].fillna(median_val, inplace=True)
                print(f"Filled missing values in '{col}' with median: {median_val:.2f}")

        # Save cleaned dataset
        df.to_csv(file_path, index=False)
        print(f"Saved cleaned file: {file_path}")

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

Processing: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
Saved cleaned file: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
Saved cleaned file: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
Saved cleaned file: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
Saved cleaned file: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
Processing: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
Saved cleaned file: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv

In [12]:
for file_path in file_paths:
    print(f"Checking missing values in: {file_path}")

    try:
        df = pd.read_csv(file_path)

        # Calculate percentage of missing values per column
        missing_ratio = df.isnull().mean() * 100
        missing_ratio = missing_ratio[missing_ratio > 0].sort_values(ascending=False)

        if missing_ratio.empty:
            print("No missing values found.")
        else:
            print(f"Columns with missing values ({len(missing_ratio)}):")
            print(missing_ratio)

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
No missing values found.

In [13]:
for file_path in file_paths:
    print(f"Final filling for: {file_path}")

    try:
        df = pd.read_csv(file_path)

        age_cols = [
            col
            for col in df.columns
            if col.startswith("age") and df[col].isnull().any()
        ]
        for col in age_cols:
            # Extract the part before the dash, convert to numeric
            df[col] = df[col].astype(str).str.extract(r"^(\d+)")[0]
            df[col] = pd.to_numeric(df[col], errors="coerce")

            if df[col].isnull().any():
                median_age = df[col].median()
                df[col].fillna(median_age, inplace=True)
                print(f"Cleaned and filled '{col}' with median: {median_age:.1f}")

        nation_cols = [
            col
            for col in df.columns
            if col.startswith("nation") and df[col].isnull().any()
        ]
        for col in nation_cols:
            mode_nation = (
                df[col].mode().iloc[0] if not df[col].mode().empty else "Unknown"
            )
            df[col].fillna(mode_nation, inplace=True)
            print(f"Filled '{col}' with mode: {mode_nation}")

        df.to_csv(file_path, index=False)
        print(f"All cleaned and saved: {file_path}")

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

Final filling for: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
All cleaned and saved: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
Final filling for: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
All cleaned and saved: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
Final filling for: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
All cleaned and saved: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
Final filling for: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
All cleaned and saved: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
Final filling for: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
All cleaned and saved: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv

In [14]:
for file_path in file_paths:
    print(f"Checking missing values in: {file_path}")

    try:
        df = pd.read_csv(file_path)
        total_missing = df.isnull().sum().sum()
        if total_missing == 0:
            print("No missing values found.")
        else:
            print(f"Still {int(total_missing)} missing values.")
            print("Columns with missing values:")
            print(df.isnull().sum()[df.isnull().sum() > 0])
    except Exception as e:
        print(f"Error loading {file_path}: {e}")

Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_premier_league_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_laliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_bundesliga_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_ligue1_2020_2024.csv
No missing values found.
Checking missing values in: ../data/fbref_cleaned_post_scrapping/merged_serieA_2020_2024.csv
No missing values found.